<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mobile Postpaid</name>
   <tag></tag>
   <elementGuidId>a0450ffc-ff9e-4d55-8a96-d1ee3e2ed489</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-app-body']/main/section/ui-view/sct-shop-widget/div/div[2]/div/nav/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Mobile Postpaid&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6324bb0f-c80c-4dd7-90fc-48e6938d9e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>51c4ab5e-93b5-49ee-a938-d6be7067583a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-nav-vertical-item</value>
      <webElementGuid>fc4e31dd-9141-4983-b888-cecff5ab894a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>05efb6a3-662d-4b7f-b79b-7474de3884a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobile Postpaid</value>
      <webElementGuid>374a337c-8026-41a6-8085-5b1161bccfd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-app-body&quot;)/main[1]/section[1]/ui-view[@class=&quot;ng-star-inserted&quot;]/sct-shop-widget[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/nav[@class=&quot;w-nav-vertical px-2 mr-4 col-md-2&quot;]/div[@class=&quot;mb-4 ng-star-inserted&quot;]/div[@class=&quot;mb-2 ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;w-nav-vertical-item&quot;]</value>
      <webElementGuid>d870fd9d-f5ea-4562-be1a-8b56bc29c94f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-app-body']/main/section/ui-view/sct-shop-widget/div/div[2]/div/nav/div/div[2]/div/a</value>
      <webElementGuid>e407c5df-92a1-4b7a-ac91-497ae830bf6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mobile Postpaid')]</value>
      <webElementGuid>95d7ab99-e15f-4245-b526-3c12ce1eca50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postpaid plans'])[1]/following::a[1]</value>
      <webElementGuid>6169441f-d8ab-4e90-8bef-c7d760a93c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile prepaid'])[1]/following::a[2]</value>
      <webElementGuid>7672d64d-8b0d-4545-8f21-ee199d523bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Broadband'])[1]/preceding::a[1]</value>
      <webElementGuid>acced6e3-3b57-4a24-b453-f55293b53906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fixedline'])[1]/preceding::a[2]</value>
      <webElementGuid>2fab1a1d-f37d-454c-b324-50e628f32096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mobile Postpaid']/parent::*</value>
      <webElementGuid>5ae54166-0104-4df2-8835-84fce1e22971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>129ce312-af2a-46b2-95e4-41a9bda30b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/a</value>
      <webElementGuid>5415bbd5-87c7-4eb0-af88-a352c2aa7bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Mobile Postpaid' or . = 'Mobile Postpaid')]</value>
      <webElementGuid>f11d1036-4a92-4372-8c18-6abeb638b07e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
