<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Identification details</name>
   <tag></tag>
   <elementGuidId>737f5047-ad66-49ff-a662-023ef044fefd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='5d51f803-5edf-4526-b992-957243aaa00e']/div/div/sct-modal-header/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Identification details×&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a4fc92cc-cf41-4e77-8c9c-cdce5cc998df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-header</value>
      <webElementGuid>490599a5-c924-419a-ac05-052a7c346c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Identification details×</value>
      <webElementGuid>ac913852-135e-4420-92d3-dc0359a8bc42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5d51f803-5edf-4526-b992-957243aaa00e&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/sct-modal-header[1]/div[@class=&quot;modal-header&quot;]</value>
      <webElementGuid>0b0f9657-314f-432d-999b-692979285522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5d51f803-5edf-4526-b992-957243aaa00e']/div/div/sct-modal-header/div</value>
      <webElementGuid>17bed4b1-12de-412a-9deb-160622d3ee90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Execute flowable'])[1]/following::div[5]</value>
      <webElementGuid>8da827e9-ba42-4fe5-8ae7-81b582124b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acquire customer information'])[1]/following::div[5]</value>
      <webElementGuid>a0c5b8c3-6868-476b-ab5c-c1e67ef801f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sct-modal-header/div</value>
      <webElementGuid>a723ddaa-303b-45f7-8b37-0f96182ca882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Identification details×' or . = 'Identification details×')]</value>
      <webElementGuid>a67dc676-7019-4462-bb6d-fb31468e5552</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
