<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Identification details</name>
   <tag></tag>
   <elementGuidId>aedffd37-f292-4468-b197-756c328b4abb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.modal-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='5d51f803-5edf-4526-b992-957243aaa00e']/div/div/sct-modal-header/div/span/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Identification details&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>7ea5cc99-f3fd-4174-b9f2-c382860e755d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>ea81864e-92f1-4068-86ed-bdfed96be3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Identification details</value>
      <webElementGuid>6f83898d-bb58-4d92-a621-5c77ad5b2bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5d51f803-5edf-4526-b992-957243aaa00e&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/sct-modal-header[1]/div[@class=&quot;modal-header&quot;]/span[@class=&quot;d-flex&quot;]/h3[@class=&quot;modal-title&quot;]</value>
      <webElementGuid>3600f978-5ebe-4d93-9359-0588e7e18b7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5d51f803-5edf-4526-b992-957243aaa00e']/div/div/sct-modal-header/div/span/h3</value>
      <webElementGuid>972acc13-820f-486b-8349-2d751094cdca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Execute flowable'])[1]/following::h3[1]</value>
      <webElementGuid>b70bf6b4-69c9-4052-a271-9a500c7c0c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acquire customer information'])[1]/following::h3[1]</value>
      <webElementGuid>fdf88024-8a1d-4c5c-8209-bb0d0a4bf87a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::h3[1]</value>
      <webElementGuid>8c08ae93-f555-45b8-a503-cfa7d476ca1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identification type'])[1]/preceding::h3[1]</value>
      <webElementGuid>d02de405-d060-4e05-b2ae-1dea49faae3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Identification details']/parent::*</value>
      <webElementGuid>9f8fb7b3-97a5-4cb7-b306-f16c696108d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>8602e6bc-1fed-4cfd-8ca4-4f547395d547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Identification details' or . = 'Identification details')]</value>
      <webElementGuid>6d2906d7-aa39-4b54-9fbe-3783dbdd8dab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
