<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Qvantel Postpaid Subscription</name>
   <tag></tag>
   <elementGuidId>a5d7f2c5-0f58-4cb8-b40a-dc9b4717f87d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Qvantel Postpaid Subscription']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Qvantel Postpaid Subscription&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6fb93f6a-fe71-45dc-a5b7-49ed673f12a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-1</value>
      <webElementGuid>105d7c71-dc41-40ff-ab2a-555efa2c438a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Qvantel Postpaid Subscription</value>
      <webElementGuid>4caad895-df47-4daa-b947-7a132a523e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cell-orderItems-1e05047e-abf7-490a-a2b3-2fb1b8b90a0a-line-0&quot;)/span[@class=&quot;mr-1&quot;]</value>
      <webElementGuid>e15d243b-65af-49fa-8e48-899c82961a46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cell-orderItems-1e05047e-abf7-490a-a2b3-2fb1b8b90a0a-line-0']/span[2]</value>
      <webElementGuid>041bcc82-36d0-4d0a-b215-a9486187974e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::span[1]</value>
      <webElementGuid>58d497b4-b73e-40f2-a658-070b48a95ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[2]/following::span[2]</value>
      <webElementGuid>8506e06e-a02c-48c2-ad9c-c08b873b7891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed'])[3]/preceding::span[1]</value>
      <webElementGuid>abe87f52-a545-4494-9d60-723572ae3e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer care'])[2]/preceding::span[3]</value>
      <webElementGuid>3b2d9cd2-bf28-4788-b980-883543315575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Qvantel Postpaid Subscription']/parent::*</value>
      <webElementGuid>26845ec1-7be9-4913-9d00-54fb9677fd08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/span[2]</value>
      <webElementGuid>500cd781-f104-41b1-b2cf-0913d826b194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Qvantel Postpaid Subscription' or . = 'Qvantel Postpaid Subscription')]</value>
      <webElementGuid>dd72336d-af36-45e5-b0f7-3eb2fae50dc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
