<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logoutnm_ng-tns-c262-2</name>
   <tag></tag>
   <elementGuidId>c2470ff7-82b3-40fd-9c02-3e96c3592a36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Tom Tamer'])[4]/following::a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ng-tns-c262-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>222172e0-9941-4753-bf13-d9e18328be73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>1974ccc2-5ae7-42c2-9ad7-6cad54da4beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c262-2</value>
      <webElementGuid>ff0fc4df-6832-4c70-9e40-56b5da59edb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-app&quot;)/sct-context-customer[@class=&quot;ng-tns-c262-2 ng-star-inserted&quot;]/div[@class=&quot;f-context--wrapper ng-tns-c262-2 ng-star-inserted&quot;]/nav[@class=&quot;w-nav-context f-nav-context--prepend f-nav-context--active-context-on-page ng-tns-c262-2&quot;]/a[@class=&quot;ng-tns-c262-2&quot;]</value>
      <webElementGuid>832a2256-1f6a-4c80-95ed-b92860662149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-app']/sct-context-customer/div/nav/a</value>
      <webElementGuid>71bbe019-9867-444f-b19c-502a900bf9fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logoutnm'])[1]/following::a[1]</value>
      <webElementGuid>b5bbee6c-4f96-477a-8653-88732f1d2d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tom Tamer'])[4]/following::a[2]</value>
      <webElementGuid>b1c81a03-6e25-4152-bda6-d67d7ce753d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pradise 999'])[2]/preceding::a[1]</value>
      <webElementGuid>40ab22c5-c02b-49ed-8ccc-3f0682d7feb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pradise 999'])[3]/preceding::a[1]</value>
      <webElementGuid>2fba72fe-168e-4aec-9855-f4ecf1cd8a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>b033afa4-884b-4234-9c0e-475767fa28a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/a</value>
      <webElementGuid>662c5229-1520-4175-9851-50303112b457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;']</value>
      <webElementGuid>a6378009-b1c0-4d57-aded-523e960b187d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
