<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_No previously stored customer info found. Continue by defining a new customer</name>
   <tag></tag>
   <elementGuidId>e826e7f8-c967-4f20-96ac-1e75226ee644</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//sct-form-dd-alert[@id='952b7a19-f572-489a-a119-838c63bd33ca']/div/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.mb-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;No previously stored customer info found. Continue by defining a new customer.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>616622f2-0405-4517-bade-556146d46b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-0</value>
      <webElementGuid>6fbdf287-4025-4851-8cb3-2a30afc0a286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No previously stored customer info found. Continue by defining a new customer.</value>
      <webElementGuid>d5c13e36-f9a1-42c8-b5bf-7cfca0bbf1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;952b7a19-f572-489a-a119-838c63bd33ca&quot;)/div[@class=&quot;alert-container&quot;]/div[@class=&quot;alert alert-success mb-0 ng-star-inserted&quot;]/div[@class=&quot;alert-body&quot;]/div[@class=&quot;alert-body-content&quot;]/p[@class=&quot;mb-0&quot;]</value>
      <webElementGuid>0a4ce4b4-8fd0-485d-a440-754106ec867b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//sct-form-dd-alert[@id='952b7a19-f572-489a-a119-838c63bd33ca']/div/div/div/div/p</value>
      <webElementGuid>284bfe47-ba60-4f1a-ae3e-fdb7b49c90eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Captured identity'])[1]/following::p[1]</value>
      <webElementGuid>5b712f4a-0a29-478b-a21a-e8e91a4dbfc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::p[1]</value>
      <webElementGuid>d8b9f80b-fc4e-4e80-9117-7d720e256cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identification type'])[1]/preceding::p[1]</value>
      <webElementGuid>f4f13006-f755-47ea-a4b3-2b2da56f8c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Driving license'])[1]/preceding::p[1]</value>
      <webElementGuid>dd7d39f0-47f7-445a-bf37-06b316b74594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No previously stored customer info found. Continue by defining a new customer.']/parent::*</value>
      <webElementGuid>5f4c0242-fd23-4881-b2a2-7393e0960721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>f49a82e3-6d0f-4b6b-b260-ecb7d2208a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'No previously stored customer info found. Continue by defining a new customer.' or . = 'No previously stored customer info found. Continue by defining a new customer.')]</value>
      <webElementGuid>39fdc6cc-f2b9-436f-ac23-ac83df7b2861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
