<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Overview</name>
   <tag></tag>
   <elementGuidId>2716a20f-b25d-42af-8a14-5cff3c99d5c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-app']/nav/sct-navigation/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>sct-navigation.w-nav-primary.ml-0.mr-0 > ul > li.ng-star-inserted > a.d-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Overview&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3060f349-3ef0-4353-bf0d-a9b824ae296b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-block</value>
      <webElementGuid>a8da3027-8374-40ca-842c-8b8eecf22b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-state</name>
      <type>Main</type>
      <value>customer.overview</value>
      <webElementGuid>56aad7c9-11e4-43cf-8b61-fa2afe73c6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ba0412f3-08e8-444f-b925-9b748be90f7c/overview</value>
      <webElementGuid>262174e3-2e98-4f7d-96fd-6968827bc9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Overview</value>
      <webElementGuid>ac76485a-ddeb-48ff-8206-0cd46fc13955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-app&quot;)/nav[@class=&quot;w-nav-primary f-nav-primary d-md-block ng-star-inserted d-none&quot;]/sct-navigation[@class=&quot;w-nav-primary ml-0 mr-0&quot;]/ul[1]/li[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;d-block&quot;]</value>
      <webElementGuid>50486418-620c-4ece-a5ee-72fa20187e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-app']/nav/sct-navigation/ul/li/a</value>
      <webElementGuid>262dcd8a-a601-4e6b-bfc4-f224c663c138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perform Payment'])[1]/following::a[1]</value>
      <webElementGuid>b2ade1c5-0315-4ce3-9c45-1a24662069d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close customer session'])[1]/following::a[2]</value>
      <webElementGuid>3b026995-cc2c-4dec-9b6a-8b2cddbd3cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[2]/preceding::a[1]</value>
      <webElementGuid>bb17c9c5-c2ed-4990-8700-a10f5a4ec99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/ba0412f3-08e8-444f-b925-9b748be90f7c/overview')])[2]</value>
      <webElementGuid>68fd2f70-a8da-4dae-81b9-fea0d21c9328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/nav/sct-navigation/ul/li/a</value>
      <webElementGuid>1e0ed2bd-dca7-4cca-bbe2-f4db4c85d105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ba0412f3-08e8-444f-b925-9b748be90f7c/overview' and (text() = 'Overview' or . = 'Overview')]</value>
      <webElementGuid>712b604d-a43b-4357-bdba-b38ef46558a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
