<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_srjgmail.com</name>
   <tag></tag>
   <elementGuidId>545466e3-0c2c-4fd1-9fae-e345b56e7b24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Main'])[2]/following::span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cell-contactMediaType-4a229247-4362-4113-b6b9-0af776cd3c68-line-0 > span > sct-non-empty.ng-tns-c257-18.ng-star-inserted > span.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;srj@gmail.com&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5d833419-3224-421c-8052-bb96af9b5d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>e2a6594f-7bc6-4bd4-a3f4-8efa1d6e0dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>srj@gmail.com</value>
      <webElementGuid>2eb69de5-fb38-44ae-91d4-9be3d010dca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cell-contactMediaType-4a229247-4362-4113-b6b9-0af776cd3c68-line-0&quot;)/span[1]/sct-non-empty[@class=&quot;ng-tns-c257-18 ng-star-inserted&quot;]/span[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>1a592752-4178-4e92-bf12-0bbd9331423e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cell-contactMediaType-4a229247-4362-4113-b6b9-0af776cd3c68-line-0']/span/sct-non-empty/span</value>
      <webElementGuid>dabd9c31-d9d9-4009-8a16-17804b4fda77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main'])[2]/following::span[2]</value>
      <webElementGuid>e2083040-15f9-484b-bdb4-d2e92c0b4243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address'])[1]/following::span[3]</value>
      <webElementGuid>5a039b03-a462-463f-b210-1d3e07a79926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contracts'])[1]/preceding::span[2]</value>
      <webElementGuid>c2918c45-7e83-491a-b93f-3e3deb60126c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No contracts found'])[1]/preceding::span[2]</value>
      <webElementGuid>1f5a45d5-f992-4943-8f89-913aedba4b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='srj@gmail.com']/parent::*</value>
      <webElementGuid>867e290d-7dd3-48be-978a-119a95ce1d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/div/span/sct-non-empty/span</value>
      <webElementGuid>1c21a80f-4cf6-4ada-b91c-2ea11b9c800b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'srj@gmail.com' or . = 'srj@gmail.com')]</value>
      <webElementGuid>3e19ce00-e43a-4f31-995b-ac61d1940962</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
