<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mobile Postpaid</name>
   <tag></tag>
   <elementGuidId>a7c542b9-d151-4927-bccd-42b466b3eaf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-app-body']/main/section/ui-view/sct-shop-widget/div/div[2]/div/nav/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Mobile Postpaid&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>33dd42ea-74d1-4583-b2e1-3687694fc6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>baf0e0fe-3401-4cac-a636-da9192d46b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-nav-vertical-item</value>
      <webElementGuid>8aee53ee-8aaf-45f9-82f6-613d2fab7057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>18fe5de6-eaad-4c6c-a3d8-07e8b40a1662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobile Postpaid</value>
      <webElementGuid>f68dc16a-5138-40a4-943b-b05318d5a5b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-app-body&quot;)/main[1]/section[1]/ui-view[@class=&quot;ng-star-inserted&quot;]/sct-shop-widget[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/nav[@class=&quot;w-nav-vertical px-2 mr-4 col-md-2&quot;]/div[@class=&quot;mb-4 ng-star-inserted&quot;]/div[@class=&quot;mb-2 ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;w-nav-vertical-item&quot;]</value>
      <webElementGuid>181c7d02-f301-4a4f-a3ee-a783171faef0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-app-body']/main/section/ui-view/sct-shop-widget/div/div[2]/div/nav/div/div[2]/div/a</value>
      <webElementGuid>11423484-e329-4ede-b620-d04548db2610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mobile Postpaid')]</value>
      <webElementGuid>494d054e-6c02-4191-b55e-dd756b41874d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postpaid plans'])[1]/following::a[1]</value>
      <webElementGuid>fbb48538-aa11-4c8a-aa71-3dc82e778598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile prepaid'])[1]/following::a[2]</value>
      <webElementGuid>23f9b118-05da-4b98-8e40-82a26b0241f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Broadband'])[1]/preceding::a[1]</value>
      <webElementGuid>2de4bf6f-b55b-4dd4-9ce6-8c014f4b2b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fixedline'])[1]/preceding::a[2]</value>
      <webElementGuid>83fa8e16-c0b6-4695-94e7-70fc2a010010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mobile Postpaid']/parent::*</value>
      <webElementGuid>7ae506e5-98cf-4b46-8cf0-f7595154e90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>33c5acb6-1c6a-42f3-a975-9f9e679c3b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/a</value>
      <webElementGuid>e1df0a3a-2572-4fe4-923c-602f710f8745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Mobile Postpaid' or . = 'Mobile Postpaid')]</value>
      <webElementGuid>5c85e5f6-5d29-47b3-8ed2-2c09eee25596</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
