<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm</name>
   <tag></tag>
   <elementGuidId>6dccf3cc-1a52-47eb-bdd1-c658a202c88c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit' and (text() = ' Confirm ' or . = ' Confirm ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>sct-flowable >> internal:has-text=&quot;Geo Localization consent False True Own Marketing consent False True 3rd Party M&quot;i >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aaa4d2c7-d0c9-4858-91e4-47c4b8748c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>29b98a55-a762-4e8c-a01c-66db9998c2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary ng-star-inserted</value>
      <webElementGuid>accb4d47-c1a1-4713-8341-8d9e687fdd75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>btn-primary</value>
      <webElementGuid>549cab1c-9c57-4740-811c-79ff89c1aeed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Confirm </value>
      <webElementGuid>80353112-b13b-4ba6-a6b0-ecf24570494d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flex-wizard&quot;)/div[@class=&quot;d-flex col-xl-12 ng-star-inserted&quot;]/div[@class=&quot;col-xl-6&quot;]/span[@class=&quot;ng-star-inserted&quot;]/sct-flex-wizard-component-renderer[1]/div[@class=&quot;f-util-border-2 ng-star-inserted&quot;]/sct-flowable[@class=&quot;col-xl-12 mb-0 mt-0 mr-0 ml-0 d28d6ac7-24f4-4c83-9748-5c3550f5c5e2 ng-star-inserted&quot;]/div[@class=&quot;d-flex justify-content-between position-static ng-star-inserted&quot;]/div[2]/button[@class=&quot;btn btn-primary ng-star-inserted&quot;]</value>
      <webElementGuid>cf05e70c-99f1-4284-a6fc-1650247fba31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>12ae3817-4264-4f25-b19c-b1cadb7e5b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flex-wizard']/div/div/span[2]/sct-flex-wizard-component-renderer/div[2]/sct-flowable/div[2]/div[2]/button</value>
      <webElementGuid>e16e4d93-3376-4088-8215-e0439c6aed66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='True'])[6]/following::button[1]</value>
      <webElementGuid>91523f6f-2ed4-4338-a051-68fc29d3a015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='False'])[6]/following::button[1]</value>
      <webElementGuid>2851c9c0-f630-4b2d-b427-55d1addd9f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select term'])[1]/preceding::button[1]</value>
      <webElementGuid>61eb6411-0c3a-441c-b8f6-482f16027eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qvantel Super'])[1]/preceding::button[1]</value>
      <webElementGuid>9bd06064-2138-445b-b92a-b4a5acfafd56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm']/parent::*</value>
      <webElementGuid>54ffc80b-8a91-49af-8ade-864957162b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>393d46a2-fd51-45d0-a7de-d1afb60a5618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Confirm ' or . = ' Confirm ')]</value>
      <webElementGuid>9fe0abbc-61a2-4d70-bf54-d456adf3f19f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
