<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select</name>
   <tag></tag>
   <elementGuidId>72cf0db4-1603-43f2-86f4-b81eb958079c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Select&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4f1171bd-0098-46d3-9194-8d51a2fa5742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>da557f46-4f7c-409e-a118-84a25037df80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary ng-star-inserted</value>
      <webElementGuid>bd69694c-d324-4f06-b53a-78fe4d838863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>btn-primary</value>
      <webElementGuid>229bce34-969c-46dc-83a4-8d22d5acfeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Select </value>
      <webElementGuid>0b412e5e-a089-4fe1-8e68-2d65172df7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flex-wizard&quot;)/div[@class=&quot;d-flex col-xl-12 ng-star-inserted&quot;]/div[@class=&quot;col-xl-6&quot;]/span[@class=&quot;ng-star-inserted&quot;]/sct-flex-wizard-component-renderer[1]/div[@class=&quot;f-util-border-2 ng-star-inserted&quot;]/sct-flowable[@class=&quot;col-xl-12 mb-0 mt-0 mr-0 ml-0 ca0b068a-7952-4977-8e07-f151c38a9068 ng-star-inserted&quot;]/div[@class=&quot;d-flex justify-content-between position-static ng-star-inserted&quot;]/div[2]/button[@class=&quot;btn btn-primary ng-star-inserted&quot;]</value>
      <webElementGuid>41f83e6a-39fb-47ed-8f7b-596aafc59b2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>7ddedd73-54ca-431c-aee8-4656e22817e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flex-wizard']/div/div/span/sct-flex-wizard-component-renderer/div[2]/sct-flowable/div[2]/div[2]/button</value>
      <webElementGuid>0c9eff41-da94-4351-9165-53be4b5962c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valid to'])[1]/following::button[2]</value>
      <webElementGuid>792c54b1-dc3c-469c-ae1f-dab2805a476e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valid from'])[1]/following::button[3]</value>
      <webElementGuid>c9036435-99cd-4373-8a05-7983dc8ab9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure marketing permissions'])[1]/preceding::button[1]</value>
      <webElementGuid>f0778fd3-b35f-446e-b7bc-aeb30224ba8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geo Localization consent'])[1]/preceding::button[1]</value>
      <webElementGuid>2aa9c3e6-38f9-46a2-a416-acf6947665c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>cff7b475-4115-4c4f-a47a-e3232a0ecfec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>5f613f0b-9858-42df-a109-b8d55cfd358e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Select ' or . = ' Select ')]</value>
      <webElementGuid>0f794dec-deb2-498d-bb3b-391cee7bbc84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
