<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postal code_postalCode</name>
   <tag></tag>
   <elementGuidId>9dd776ac-fa0d-46d9-a078-28f805cd7d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postalCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='postalCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Postal code&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90890637-ffa4-447d-81e3-9c071c9f7a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control sct-form-text ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>38bfd90d-b6dd-4f9a-83f5-7db7abfd781a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>7afd8817-19d0-400f-bd34-0a7a7863f7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>postalCode</value>
      <webElementGuid>4eb7f0e1-16e0-4eb2-9d6c-fc222e0db7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>postalCode</value>
      <webElementGuid>e08dd2f9-388f-4be6-9a92-30279730aecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>postalCode</value>
      <webElementGuid>c83927f2-fd6b-45d5-81b2-a6acaadb21da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df47ec20-e016-4942-8a4e-bbfce3cd2864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postalCode&quot;)</value>
      <webElementGuid>df6d4a4a-9f41-4d3d-ac52-7b84522ca941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='postalCode']</value>
      <webElementGuid>54bad0fd-454b-4e87-9435-ea336270930f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//sct-form-dd-input[@id='df8a3da5-1b77-442b-a098-f57dd8246128']/div/div/input</value>
      <webElementGuid>cc166fad-623a-4ccc-8d19-977a6f0d439e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/sct-form-dd-input/div/div/input</value>
      <webElementGuid>77abb972-820b-424f-b037-4d2502fefadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'postalCode' and @name = 'postalCode' and @type = 'text']</value>
      <webElementGuid>5a0f938e-fbf7-448c-a6cf-be341a5e9f1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
