<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Given Name_givenName</name>
   <tag></tag>
   <elementGuidId>1cc9d295-07e8-4b9a-a9dc-960006d1aa26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#givenName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='givenName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Given Name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc6b0342-9881-4771-9d7f-b9cc54a40b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control sct-form-text ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>cad4746a-67b7-4e6a-92bc-6245a1d1d6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>265bbe00-05e5-4cc7-9770-1a60b8638736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>givenName</value>
      <webElementGuid>17cdcd31-6d0b-40d4-901b-17f47e02ed6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>givenName</value>
      <webElementGuid>db77c310-8574-4174-93a1-c65211803ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>givenName</value>
      <webElementGuid>a893a922-90c5-46c9-a092-1b1347b92f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2412d4e4-9d72-4d6d-b12c-95e8c971c8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;givenName&quot;)</value>
      <webElementGuid>658d19cb-9167-49ef-9e7c-3dfd7f5d9f13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='givenName']</value>
      <webElementGuid>b2ec078f-3f39-40c6-aaf1-4326dba24ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//sct-form-dd-input[@id='f3668f39-469e-4227-91cd-add141556bad']/div/div/input</value>
      <webElementGuid>10c92b87-68dd-4b37-81cd-86f7988662ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sct-form-dd-input/div/div/input</value>
      <webElementGuid>781456ee-053c-4006-89f4-fe63aa38b6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'givenName' and @name = 'givenName' and @type = 'text']</value>
      <webElementGuid>27d5faa2-35cc-4191-9c85-2ea71fe5be55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
