<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street_street</name>
   <tag></tag>
   <elementGuidId>d47d373f-122d-4783-8af3-f6ff204ef04b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#street</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='street']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Street&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>818a03dd-71fa-401a-8fb7-b6f31c010426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control sct-form-text ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>66ab9a1b-4c20-4944-9c10-1db64890f068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>cddaefb5-0116-458f-b51c-5601e7753393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>street</value>
      <webElementGuid>24cb73fb-aeb2-458c-9832-9e2daf37d75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>street</value>
      <webElementGuid>2b68f349-e4e5-4b7a-ab82-6795bf5f02d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>street</value>
      <webElementGuid>c9a492e6-19df-4854-b6b7-2343af93162f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1105f5cd-4f43-4fc1-8e3f-eaa802a6c2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;street&quot;)</value>
      <webElementGuid>99b57509-389c-46bd-92d9-33b1079700fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='street']</value>
      <webElementGuid>8892932e-9264-4450-90b8-8fde5e74a01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//sct-form-dd-input[@id='e023fb4b-50b7-4664-9f40-fa4940f73b4a']/div/div/input</value>
      <webElementGuid>511d380a-c10b-489f-8b6b-e56e26017625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/sct-form-dd-input[2]/div/div/input</value>
      <webElementGuid>5985b0f9-bca6-4829-8864-dbc781edfe93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'street' and @name = 'street' and @type = 'text']</value>
      <webElementGuid>2ace1baa-2873-4581-a91a-aae92e0e38fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
