<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FamilyName_familyName</name>
   <tag></tag>
   <elementGuidId>dcc9098f-504f-4a29-b1a0-f4533faee306</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'familyName' and @name = 'familyName' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#familyName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='familyName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;FamilyName&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cd14273-cfdd-4db2-93a1-ae5a222009ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control sct-form-text ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>44b8bc1d-a97a-4273-8efc-4bba3228dbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>dd7850bf-af86-44b1-9141-0abb76930264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>familyName</value>
      <webElementGuid>f333ce03-4288-46ec-aaa0-2910994bfdc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>familyName</value>
      <webElementGuid>b966324b-7de9-4ef6-ab22-62543ef87d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>familyName</value>
      <webElementGuid>54954852-7f5f-4286-9e37-2ec080d8bc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43449bf7-346e-4c3b-ac5f-ea028c2850a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;familyName&quot;)</value>
      <webElementGuid>8e23e7ad-ae7a-4c0f-8af2-36abe9327d6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='familyName']</value>
      <webElementGuid>6e82a99b-e35a-404a-bb45-b52072ff0140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//sct-form-dd-input[@id='5f45246b-0571-46ea-9453-f4fec34c9712']/div/div/input</value>
      <webElementGuid>2f4f3e25-2ef1-4358-a5f0-1b69ff088786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sct-form-dd-input[2]/div/div/input</value>
      <webElementGuid>edb21c25-619d-4147-826c-a2697a4c3edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'familyName' and @name = 'familyName' and @type = 'text']</value>
      <webElementGuid>b8b938d1-6cdb-4168-9a78-6ecb27acf6e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
