<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Issuing authority_issuingAuthority</name>
   <tag></tag>
   <elementGuidId>38152308-8ffa-4a97-9295-341f3b868218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#issuingAuthority</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='issuingAuthority']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Issuing authority&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a24701a-ba90-4ba5-bf37-86a3e697a3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control sct-form-text ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>2f9eeabf-b675-4008-99e1-ee443ae298fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>51b0669f-3944-430c-9465-044a7eaca059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>issuingAuthority</value>
      <webElementGuid>6cde344f-1dce-4611-9204-aaf22d67b194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>issuingAuthority</value>
      <webElementGuid>fdbf36b4-839f-4105-baa3-4e3d93056cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>issuingAuthority</value>
      <webElementGuid>e9f5c9e9-df3e-4b33-93b6-c52cfddd2340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71459e75-8697-41aa-a9ce-f5ee1070222a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;issuingAuthority&quot;)</value>
      <webElementGuid>e1477bff-cb0f-4c2e-ab8f-86a5bf7b7eec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='issuingAuthority']</value>
      <webElementGuid>b913d2f0-851f-4860-b148-3ab96ad87e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//sct-form-dd-input[@id='1459ad4e-1571-49b2-8757-20234be78eca']/div/div/input</value>
      <webElementGuid>8e8dd8fd-ff5c-4bcc-a829-3ca7a428662b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/sct-form-dd-input/div/div/input</value>
      <webElementGuid>4f163ed4-f5e2-4de8-98c4-a8d59ec435f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'issuingAuthority' and @name = 'issuingAuthority' and @type = 'text']</value>
      <webElementGuid>40b82f88-cbaa-4107-8d51-5940001fd777</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
