<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>legend_Basket Details</name>
   <tag></tag>
   <elementGuidId>a7131fce-df63-4608-ae19-c0309f5fb108</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>legend.h4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::legend[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Basket Details&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>legend</value>
      <webElementGuid>5db6c398-f8d4-48a0-8d7a-ce1a95d8f73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>0c6f7b15-ae08-44fa-848e-6063ce6be1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Basket Details</value>
      <webElementGuid>0f8f90db-555a-47ba-8b42-7a2126fbcbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aee86310-5f95-4f3b-b0f4-d9c14d68e374&quot;)/legend[@class=&quot;h4&quot;]</value>
      <webElementGuid>6ed7759f-b853-45c8-a594-412022e5303c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//sct-form-dd-header[@id='aee86310-5f95-4f3b-b0f4-d9c14d68e374']/legend</value>
      <webElementGuid>17972503-69a7-4fa3-aa4e-a965e7becf6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::legend[1]</value>
      <webElementGuid>a14289c7-50f4-4800-821f-0b7cc48ae9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Methods'])[1]/following::legend[1]</value>
      <webElementGuid>14706a2f-4451-4bdf-b5e2-ead0b4c3a06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item'])[1]/preceding::legend[1]</value>
      <webElementGuid>f1b5baea-8f1e-4fd4-9324-e2bc5cd38a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay now'])[1]/preceding::legend[1]</value>
      <webElementGuid>d46d9021-e5bd-46a5-842f-f8ea63b5c7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Basket Details']/parent::*</value>
      <webElementGuid>1cdc1d9a-3043-4656-8b65-bcb421c71a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//legend</value>
      <webElementGuid>560e881b-25d6-4dda-ae5a-01cb376018c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//legend[(text() = 'Basket Details' or . = 'Basket Details')]</value>
      <webElementGuid>91d87ed1-379b-435e-8279-537f83fd8c04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
