<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select an alternative  Drivin_60f290</name>
   <tag></tag>
   <elementGuidId>29b1f9f0-edba-43a0-afb6-034c2c39eb4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#generatedFormSingleSelect_idType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='generatedFormSingleSelect_idType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Identification type&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>08387c38-c647-42f0-a7a7-4ccd67bbe4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select sct-form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>42331957-1b31-41da-bfd0-8965c4d38f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>generatedFormSingleSelect_idType</value>
      <webElementGuid>9d7854b5-afbb-4e61-9df3-f3a2196fdf59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>212f877c-378e-43bd-ae44-1ad021c147d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>generatedFormSingleSelect_idTy</value>
      <webElementGuid>b04048da-fd2c-4aca-a187-70495973fcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select an alternative  Driving license  Personal identity code  ID card  Passport </value>
      <webElementGuid>31dfaaa3-23fe-44a0-8155-b4db1ee9e5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generatedFormSingleSelect_idType&quot;)</value>
      <webElementGuid>dd8398b9-48af-488c-b681-a981819646cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='generatedFormSingleSelect_idType']</value>
      <webElementGuid>203992f8-a6cc-4800-81ec-9ebe84c30170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//sct-form-dd-select[@id='738855a7-92b8-427a-9898-fdf9746b2c56']/div/fieldset/select</value>
      <webElementGuid>58c52ac1-57dd-40cb-b6e6-0689588c2aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identification type'])[1]/following::select[1]</value>
      <webElementGuid>ad81d76f-48c0-4e97-9a48-be6eb438f5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::select[1]</value>
      <webElementGuid>91cba924-bc26-457d-99cc-95fbc1e12aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A value is required'])[1]/preceding::select[1]</value>
      <webElementGuid>48e1e323-0357-4dde-a8de-4190d40b35d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identification code'])[1]/preceding::select[1]</value>
      <webElementGuid>7cc3c94b-7d23-494a-a33f-99b2f66c4d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ca4e0856-4c9f-40f4-8d6c-ca585ac809f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'generatedFormSingleSelect_idType' and (text() = 'Please select an alternative  Driving license  Personal identity code  ID card  Passport ' or . = 'Please select an alternative  Driving license  Personal identity code  ID card  Passport ')]</value>
      <webElementGuid>acc1a96b-617e-4916-ac85-db652fb51a02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
