<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select an alternative  Invoice</name>
   <tag></tag>
   <elementGuidId>01ca1958-116b-4459-b632-f111ddfe4b3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#generatedFormSingleSelect_paymentMethod</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='generatedFormSingleSelect_paymentMethod']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select payment method&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fb3dfda2-a2e6-484a-a593-8a9a5c22de3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select sct-form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>92af9fa1-7673-402e-a3fa-f540902bc0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>generatedFormSingleSelect_paymentMethod</value>
      <webElementGuid>0c4e2116-8c10-4492-951c-f22dd7952741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>5b4670b3-f5f4-447d-a137-ed4b40763226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>generatedFormSingleSelect_paym</value>
      <webElementGuid>b20af014-2bd4-4a9c-8ffa-b2738306a1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select an alternative  Invoice </value>
      <webElementGuid>4922cbfd-0e9d-4b7c-8703-25d6db53a334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generatedFormSingleSelect_paymentMethod&quot;)</value>
      <webElementGuid>2a2d8d78-ddcf-451b-9f2e-ac12e9f9a083</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='generatedFormSingleSelect_paymentMethod']</value>
      <webElementGuid>371e3428-45ba-4f2f-ad44-a7b6909058e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//sct-form-dd-select[@id='721f9755-a9a0-46fb-b343-8b65ee765c63']/div/fieldset/select</value>
      <webElementGuid>833fdb1b-3e82-4f07-991c-f9dcc2f54bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select payment method'])[1]/following::select[1]</value>
      <webElementGuid>8762029e-af80-4285-9238-aaae29b24216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A value is required'])[1]/preceding::select[1]</value>
      <webElementGuid>12a69691-287d-4f82-b5f4-5ca822ef656b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::select[1]</value>
      <webElementGuid>63c1d41d-7d09-4f35-b9f2-07d3b610b53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e8c72dfa-e055-46aa-b00b-f22097e7e4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'generatedFormSingleSelect_paymentMethod' and (text() = 'Please select an alternative  Invoice ' or . = 'Please select an alternative  Invoice ')]</value>
      <webElementGuid>e5a6fcbc-09be-4313-9b2d-4809355b4941</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
