<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select an alternative  Afghan_df89e8_1</name>
   <tag></tag>
   <elementGuidId>26a49768-2d69-4c88-b3fa-e344e0bff033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#generatedFormSingleSelect_country</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='generatedFormSingleSelect_country']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Country&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ac7de238-4613-41aa-a658-a10440490768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select sct-form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>04d884b6-d92b-425a-a041-fe199d381d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>generatedFormSingleSelect_country</value>
      <webElementGuid>c4e3b06f-e3ad-423e-9436-4407d40218d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>c8adf8cb-db00-4ddc-a8c9-ee1b3c55326d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>generatedFormSingleSelect_coun</value>
      <webElementGuid>1388ba08-dec9-49e7-8224-50886002cfb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select an alternative  Afghanista  Aland Islands  Albania  Algeria  American Samoa  Andorra  Angola  Anguilla  Antarctica  Antigua And Barbuda  Argentina  Armenia  Aruba  Australia  Austria  Azerbaijan  Bahamas  Bahrain  Bangladesh  Barbados  Belarus  Belgium  Belize  Benin  Bermuda  Bhutan  Bolivia  Bosnia And Herzegovina  Botswana  Bouvet Island  Brazil  British Indian Ocean Territory  Brunei Darussalam  Bulgaria  Burkina Faso  Burundi  Cambodia  Cameroon  Canada  Cape Verde  Cayman Islands  Central African Republic  Chad  Chile  China  Christmas Island  Cocos (Keeling) Islands  Colombia  Comoros  Congo  Congo, Democratic Republic  Cook Islands  Costa Rica  Cote D'Ivoire  Croatia  Cuba  Cyprus  Czech Republic  Denmark  Djibouti  Dominica  Dominican Republic  Ecuador  Egypt  El Salvador  Equatorial Guinea  Eritrea  Estonia  Ethiopia  Falkland Islands (Malvinas)  Faroe Islands  Fiji  Finland  France  French Guiana  French Polynesia  French Southern Territories  Gabon  Gambia  Georgia  Germany  Ghana  Gibraltar  Greece  Greenland  Grenada  Guadeloupe  Guam  Guatemala  Guernsey  Guinea  Guinea-Bissau  Guyana  Haiti  Heard Island &amp; Mcdonald Islands  Holy See (Vatican City State)  Honduras  Hong Kong  Hungary  Iceland  India  Indonesia  Iran, Islamic Republic Of  Iraq  Ireland  Isle Of Man  Israel  Italy  Jamaica  Japan  Jersey  Jordan  Kazakhstan  Kenya  Kiribati  Korea (the Republic of)  Korea (the Democratic People's Republic of)  Kuwait  Kyrgyzstan  Lao People's Democratic Republic  Latvia  Lebanon  Lesotho  Liberia  Libyan Arab Jamahiriya  Liechtenstein  Lithuania  Luxembourg  Macao  Macedonia  Madagascar  Malawi  Malaysia  Maldives  Mali  Malta  Marshall Islands  Martinique  Mauritania  Mauritius  Mayotte  Mexico  Micronesia, Federated States Of  Moldova  Monaco  Mongolia  Montenegro  Montserrat  Morocco  Mozambique  Myanmar  Namibia  Nauru  Nepal  Netherlands  Bonaire, Saint Eustatius and Saba  Curaçao  Sint Maarten  New Caledonia  New Zealand  Nicaragua  Niger  Nigeria  Niue  Norfolk Island  Northern Mariana Islands  Norway  Oman  Pakistan  Palau  Palestinian Territory, Occupied  Panama  Papua New Guinea  Paraguay  Peru  Philippines  Pitcairn  Poland  Portugal  Puerto Rico  Qatar  Reunion  Romania  Russian Federation  Rwanda  Saint Barthelemy  Saint Helena  Saint Kitts And Nevis  Saint Lucia  Saint Martin  Saint Pierre And Miquelon  Saint Vincent And Grenadines  Samoa  San Marino  Sao Tome And Principe  Saudi Arabia  Senegal  Serbia  Seychelles  Sierra Leone  Singapore  Slovakia  Slovenia  Solomon Islands  Somalia  South Africa  South Georgia And Sandwich Isl.  Spain  Sri Lanka  Sudan  South Sudan  Suriname  Svalbard And Jan Mayen  Swaziland  Sweden  Switzerland  Syrian Arab Republic  Taiwan  Tajikistan  Tanzania  Thailand  Timor-Leste  Togo  Tokelau  Tonga  Trinidad And Tobago  Tunisia  Turkey  Turkmenistan  Turks And Caicos Islands  Tuvalu  Uganda  Ukraine  United Arab Emirates  United Kingdom  United States  United States Outlying Islands  Uruguay  Uzbekistan  Vanuatu  Venezuela  Viet Nam  Virgin Islands, British  Virgin Islands, U.S.  Wallis And Futuna  Western Sahara  Yemen  Zambia  Zimbabwe </value>
      <webElementGuid>13c71dc5-88a6-4f2f-aebd-73611476129b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generatedFormSingleSelect_country&quot;)</value>
      <webElementGuid>55b7b1e2-503d-4ed8-ac82-44df1b9bba88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='generatedFormSingleSelect_country']</value>
      <webElementGuid>516f3031-d155-4fbb-bb7b-b36b3aeb5842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//sct-form-dd-select[@id='25e65076-6242-4b55-9ef3-ffd0bec91d24']/div/fieldset/select</value>
      <webElementGuid>9364b01d-8dda-4ec1-a5f0-dce91297432c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[1]</value>
      <webElementGuid>c2303681-ebd3-4a5a-9da3-d5dc181b9d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal address'])[1]/following::select[1]</value>
      <webElementGuid>95837eb4-94a7-4dcd-b1be-50f948877cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A value is required'])[1]/preceding::select[1]</value>
      <webElementGuid>077f3686-3238-457c-9944-d393bd3a523d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/preceding::select[1]</value>
      <webElementGuid>932807ca-1d04-4451-856a-83998508870d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/sct-form-dd-select/div/fieldset/select</value>
      <webElementGuid>2434d39e-5c22-4936-8aa9-42f928a48d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'generatedFormSingleSelect_country' and (text() = concat(&quot;Please select an alternative  Afghanista  Aland Islands  Albania  Algeria  American Samoa  Andorra  Angola  Anguilla  Antarctica  Antigua And Barbuda  Argentina  Armenia  Aruba  Australia  Austria  Azerbaijan  Bahamas  Bahrain  Bangladesh  Barbados  Belarus  Belgium  Belize  Benin  Bermuda  Bhutan  Bolivia  Bosnia And Herzegovina  Botswana  Bouvet Island  Brazil  British Indian Ocean Territory  Brunei Darussalam  Bulgaria  Burkina Faso  Burundi  Cambodia  Cameroon  Canada  Cape Verde  Cayman Islands  Central African Republic  Chad  Chile  China  Christmas Island  Cocos (Keeling) Islands  Colombia  Comoros  Congo  Congo, Democratic Republic  Cook Islands  Costa Rica  Cote D&quot; , &quot;'&quot; , &quot;Ivoire  Croatia  Cuba  Cyprus  Czech Republic  Denmark  Djibouti  Dominica  Dominican Republic  Ecuador  Egypt  El Salvador  Equatorial Guinea  Eritrea  Estonia  Ethiopia  Falkland Islands (Malvinas)  Faroe Islands  Fiji  Finland  France  French Guiana  French Polynesia  French Southern Territories  Gabon  Gambia  Georgia  Germany  Ghana  Gibraltar  Greece  Greenland  Grenada  Guadeloupe  Guam  Guatemala  Guernsey  Guinea  Guinea-Bissau  Guyana  Haiti  Heard Island &amp; Mcdonald Islands  Holy See (Vatican City State)  Honduras  Hong Kong  Hungary  Iceland  India  Indonesia  Iran, Islamic Republic Of  Iraq  Ireland  Isle Of Man  Israel  Italy  Jamaica  Japan  Jersey  Jordan  Kazakhstan  Kenya  Kiribati  Korea (the Republic of)  Korea (the Democratic People&quot; , &quot;'&quot; , &quot;s Republic of)  Kuwait  Kyrgyzstan  Lao People&quot; , &quot;'&quot; , &quot;s Democratic Republic  Latvia  Lebanon  Lesotho  Liberia  Libyan Arab Jamahiriya  Liechtenstein  Lithuania  Luxembourg  Macao  Macedonia  Madagascar  Malawi  Malaysia  Maldives  Mali  Malta  Marshall Islands  Martinique  Mauritania  Mauritius  Mayotte  Mexico  Micronesia, Federated States Of  Moldova  Monaco  Mongolia  Montenegro  Montserrat  Morocco  Mozambique  Myanmar  Namibia  Nauru  Nepal  Netherlands  Bonaire, Saint Eustatius and Saba  Curaçao  Sint Maarten  New Caledonia  New Zealand  Nicaragua  Niger  Nigeria  Niue  Norfolk Island  Northern Mariana Islands  Norway  Oman  Pakistan  Palau  Palestinian Territory, Occupied  Panama  Papua New Guinea  Paraguay  Peru  Philippines  Pitcairn  Poland  Portugal  Puerto Rico  Qatar  Reunion  Romania  Russian Federation  Rwanda  Saint Barthelemy  Saint Helena  Saint Kitts And Nevis  Saint Lucia  Saint Martin  Saint Pierre And Miquelon  Saint Vincent And Grenadines  Samoa  San Marino  Sao Tome And Principe  Saudi Arabia  Senegal  Serbia  Seychelles  Sierra Leone  Singapore  Slovakia  Slovenia  Solomon Islands  Somalia  South Africa  South Georgia And Sandwich Isl.  Spain  Sri Lanka  Sudan  South Sudan  Suriname  Svalbard And Jan Mayen  Swaziland  Sweden  Switzerland  Syrian Arab Republic  Taiwan  Tajikistan  Tanzania  Thailand  Timor-Leste  Togo  Tokelau  Tonga  Trinidad And Tobago  Tunisia  Turkey  Turkmenistan  Turks And Caicos Islands  Tuvalu  Uganda  Ukraine  United Arab Emirates  United Kingdom  United States  United States Outlying Islands  Uruguay  Uzbekistan  Vanuatu  Venezuela  Viet Nam  Virgin Islands, British  Virgin Islands, U.S.  Wallis And Futuna  Western Sahara  Yemen  Zambia  Zimbabwe &quot;) or . = concat(&quot;Please select an alternative  Afghanista  Aland Islands  Albania  Algeria  American Samoa  Andorra  Angola  Anguilla  Antarctica  Antigua And Barbuda  Argentina  Armenia  Aruba  Australia  Austria  Azerbaijan  Bahamas  Bahrain  Bangladesh  Barbados  Belarus  Belgium  Belize  Benin  Bermuda  Bhutan  Bolivia  Bosnia And Herzegovina  Botswana  Bouvet Island  Brazil  British Indian Ocean Territory  Brunei Darussalam  Bulgaria  Burkina Faso  Burundi  Cambodia  Cameroon  Canada  Cape Verde  Cayman Islands  Central African Republic  Chad  Chile  China  Christmas Island  Cocos (Keeling) Islands  Colombia  Comoros  Congo  Congo, Democratic Republic  Cook Islands  Costa Rica  Cote D&quot; , &quot;'&quot; , &quot;Ivoire  Croatia  Cuba  Cyprus  Czech Republic  Denmark  Djibouti  Dominica  Dominican Republic  Ecuador  Egypt  El Salvador  Equatorial Guinea  Eritrea  Estonia  Ethiopia  Falkland Islands (Malvinas)  Faroe Islands  Fiji  Finland  France  French Guiana  French Polynesia  French Southern Territories  Gabon  Gambia  Georgia  Germany  Ghana  Gibraltar  Greece  Greenland  Grenada  Guadeloupe  Guam  Guatemala  Guernsey  Guinea  Guinea-Bissau  Guyana  Haiti  Heard Island &amp; Mcdonald Islands  Holy See (Vatican City State)  Honduras  Hong Kong  Hungary  Iceland  India  Indonesia  Iran, Islamic Republic Of  Iraq  Ireland  Isle Of Man  Israel  Italy  Jamaica  Japan  Jersey  Jordan  Kazakhstan  Kenya  Kiribati  Korea (the Republic of)  Korea (the Democratic People&quot; , &quot;'&quot; , &quot;s Republic of)  Kuwait  Kyrgyzstan  Lao People&quot; , &quot;'&quot; , &quot;s Democratic Republic  Latvia  Lebanon  Lesotho  Liberia  Libyan Arab Jamahiriya  Liechtenstein  Lithuania  Luxembourg  Macao  Macedonia  Madagascar  Malawi  Malaysia  Maldives  Mali  Malta  Marshall Islands  Martinique  Mauritania  Mauritius  Mayotte  Mexico  Micronesia, Federated States Of  Moldova  Monaco  Mongolia  Montenegro  Montserrat  Morocco  Mozambique  Myanmar  Namibia  Nauru  Nepal  Netherlands  Bonaire, Saint Eustatius and Saba  Curaçao  Sint Maarten  New Caledonia  New Zealand  Nicaragua  Niger  Nigeria  Niue  Norfolk Island  Northern Mariana Islands  Norway  Oman  Pakistan  Palau  Palestinian Territory, Occupied  Panama  Papua New Guinea  Paraguay  Peru  Philippines  Pitcairn  Poland  Portugal  Puerto Rico  Qatar  Reunion  Romania  Russian Federation  Rwanda  Saint Barthelemy  Saint Helena  Saint Kitts And Nevis  Saint Lucia  Saint Martin  Saint Pierre And Miquelon  Saint Vincent And Grenadines  Samoa  San Marino  Sao Tome And Principe  Saudi Arabia  Senegal  Serbia  Seychelles  Sierra Leone  Singapore  Slovakia  Slovenia  Solomon Islands  Somalia  South Africa  South Georgia And Sandwich Isl.  Spain  Sri Lanka  Sudan  South Sudan  Suriname  Svalbard And Jan Mayen  Swaziland  Sweden  Switzerland  Syrian Arab Republic  Taiwan  Tajikistan  Tanzania  Thailand  Timor-Leste  Togo  Tokelau  Tonga  Trinidad And Tobago  Tunisia  Turkey  Turkmenistan  Turks And Caicos Islands  Tuvalu  Uganda  Ukraine  United Arab Emirates  United Kingdom  United States  United States Outlying Islands  Uruguay  Uzbekistan  Vanuatu  Venezuela  Viet Nam  Virgin Islands, British  Virgin Islands, U.S.  Wallis And Futuna  Western Sahara  Yemen  Zambia  Zimbabwe &quot;))]</value>
      <webElementGuid>6341d7a3-9566-4929-bf5d-9a8e983ae990</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
