<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select an alternative  Compan_88043b</name>
   <tag></tag>
   <elementGuidId>c7afde6c-fbd4-4e36-8934-1682d896b6fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#generatedFormSingleSelect_accountType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='generatedFormSingleSelect_accountType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Account type&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>468e1003-68d0-41b8-ad4c-23df9ac8402b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select sct-form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6a0a44ba-0899-4800-bafc-c2eb3b1362e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>generatedFormSingleSelect_accountType</value>
      <webElementGuid>3a9b1d8b-fa87-450c-9a78-be91492fbbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>757eaba4-d423-407d-8ae6-44390d39123e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>generatedFormSingleSelect_acco</value>
      <webElementGuid>9fe72764-6aba-4bb6-8102-5e98283e6ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select an alternative  Company  Temporary  Self-employed  Natural person </value>
      <webElementGuid>29c0684f-ca3f-44f1-9914-ccfee7d17b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generatedFormSingleSelect_accountType&quot;)</value>
      <webElementGuid>c282bce3-87d9-47c6-aa54-bfe6a63df17c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='generatedFormSingleSelect_accountType']</value>
      <webElementGuid>09b6d9a9-c666-4d8e-b60c-7561b589c2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//sct-form-dd-select[@id='9f3d52a1-cbf2-47a1-a853-c8e02728742d']/div/fieldset/select</value>
      <webElementGuid>5d1ee309-d640-4d4a-8cea-768360d13ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account type'])[1]/following::select[1]</value>
      <webElementGuid>1f009a55-b28a-40c6-a165-b9738effc89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[2]/following::select[1]</value>
      <webElementGuid>3a53904d-b3f8-4f07-985e-be7bf94afb25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A value is required'])[1]/preceding::select[1]</value>
      <webElementGuid>9cd8112a-051b-4eaa-b2c4-0a99b9d96900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Given Name'])[1]/preceding::select[1]</value>
      <webElementGuid>dc6b2809-cae4-4361-9657-b27d2beeafd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>04c856ac-ae66-46d9-87e8-9025073fe882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'generatedFormSingleSelect_accountType' and (text() = 'Please select an alternative  Company  Temporary  Self-employed  Natural person ' or . = 'Please select an alternative  Company  Temporary  Self-employed  Natural person ')]</value>
      <webElementGuid>435d71c0-513e-4c3b-a728-3bcb070fc3f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
