<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas</name>
   <tag></tag>
   <elementGuidId>ad38714c-aaaf-4184-be5f-32c1997c7a11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subscriptionContent']/sct-dynamic-component-renderer[7]/sct-aggregated-usage/div/div[2]/canvas</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>canvas</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>15db87ab-3436-4f8c-94fd-1187ded4fcc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>d7772870-8c72-4927-8e12-d705d27c6362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-datasets</name>
      <type>Main</type>
      <value>[object Object],[object Object</value>
      <webElementGuid>f3dcb9be-0e00-4fb5-bf95-82cf307e55dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-labels</name>
      <type>Main</type>
      <value>13.01.2025</value>
      <webElementGuid>655cadb8-7929-4422-8718-7acbb5ec4c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-type</name>
      <type>Main</type>
      <value>bar</value>
      <webElementGuid>15900fc2-8e14-4753-aef1-544226c339cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-options</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>245cc566-cff1-4c08-9f01-abe383301680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-plugins</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>9c962468-c94f-42c0-91dd-8c3880ad83e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-legend</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc495fe2-779d-4756-adb1-ec2e18e32369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>954</value>
      <webElementGuid>df32db06-322c-4ef2-947e-da1a7e42630f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subscriptionContent&quot;)/sct-dynamic-component-renderer[@class=&quot;ng-star-inserted&quot;]/sct-aggregated-usage[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;w-box&quot;]/div[@class=&quot;position-relative ng-star-inserted&quot;]/canvas[1]</value>
      <webElementGuid>59d75a0b-3e2f-4660-9924-66e125da3da3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subscriptionContent']/sct-dynamic-component-renderer[7]/sct-aggregated-usage/div/div[2]/canvas</value>
      <webElementGuid>2b7417ac-9a50-4f3a-a458-395cd4a3ba20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>67990bcd-0d9d-45fa-9fac-82ff44952a88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
